apiVersion: v1
kind: Pod
spec:
  containers:
    - name: bash
      image: ellerbrock/alpine-bash-curl-ssl:latest
      tty: true
      command:
        - cat
      volumeMounts:
        - name: packages
          mountPath: /data
          subPath: upstream
  securityContext:
    fsGroup: 1000
  volumes:
    - name: packages
      persistentVolumeClaim:
        claimName: packages
