apiVersion: v1
kind: Pod
spec:
  containers:
    - name: bash
      image: ellerbrock/alpine-bash-curl-ssl:latest
      volumeMounts:
        - name: upstream-releases
          mountPath: /releases
  securityContext:
    fsGroup: 1000
  volumes:
    - name: upstream-releases
      persistentVolumeClaim:
        claimName: upstream-releases
